# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/main_cons.xdc

# Block Designs: bd/MainBlockDesign/MainBlockDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainBlockDesign || ORIG_REF_NAME==MainBlockDesign} -quiet] -quiet

# IP: bd/MainBlockDesign/ip/MainBlockDesign_seg7_hex_0_0/MainBlockDesign_seg7_hex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainBlockDesign_seg7_hex_0_0 || ORIG_REF_NAME==MainBlockDesign_seg7_hex_0_0} -quiet] -quiet

# IP: bd/MainBlockDesign/ip/MainBlockDesign_seg7_hex_0_1/MainBlockDesign_seg7_hex_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainBlockDesign_seg7_hex_0_1 || ORIG_REF_NAME==MainBlockDesign_seg7_hex_0_1} -quiet] -quiet

# IP: bd/MainBlockDesign/ip/MainBlockDesign_CharToSegEncoder_0_0/MainBlockDesign_CharToSegEncoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainBlockDesign_CharToSegEncoder_0_0 || ORIG_REF_NAME==MainBlockDesign_CharToSegEncoder_0_0} -quiet] -quiet

# IP: bd/MainBlockDesign/ip/MainBlockDesign_OutputGenerator_0_0/MainBlockDesign_OutputGenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainBlockDesign_OutputGenerator_0_0 || ORIG_REF_NAME==MainBlockDesign_OutputGenerator_0_0} -quiet] -quiet

# XDC: bd/MainBlockDesign/MainBlockDesign_ooc.xdc
